In [7]:
import numpy as np
# dimession is equal or one of them is 1.
# 1. (3,2) and (3,2) True
# 2. (3,2) and (3,3) False
# 3. (3,3) and (1,3) True
x = np.random.randint(1,10,[3,3])
y = np.random.randint(1,10,[3,3])
print(x)
print(y)

# [[7 3 2] - [7 2 5]
#  [5 8 4] - [7 2 5]
#  [6 1 4]] - [7 2 5]

z = np.random.randint(1,10,3)
print(z)
# [7 2 5]

ans = x - z
print(ans)

# Transpose
x = np.random.randint(1,10,[3,2])
y = np.random.randint(1,10,[2,3])
y = np.transpose(y)
print(y.shape)
ans = x - y
print(ans)

[[5 3 2]
 [8 8 1]
 [7 3 2]]
[[8 2 6]
 [4 5 6]
 [2 2 2]]
[7 8 1]
[[-2 -5  1]
 [ 1  0  0]
 [ 0 -5  1]]
(3, 2)
[[ 4  0]
 [ 0  3]
 [-2 -2]]


In [20]:
# Resize
a=np.array([[0,1],[2,3]]) # 2x2
print(a)
a = np.resize(a,(2,3)) # repeats the elements if required to fill the vacant cells.
print(a)
a = np.resize(a,(1,4))
print(a)
a = np.zeros((10,2), dtype = int)
print(a)
new_a = np.transpose(a) # transpose
print(new_a)
new_a = a.T # transpose
print(new_a)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 0 1]]
[[0 1 2 3]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [21]:
# Reshape
a = np.arange(6).reshape((3, 2))
print(a)


array([[0, 1],
       [2, 3],
       [4, 5]])