In [4]:
import time
import numpy as np

size = 100000

## Adding elements of array a and b

def addition_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i]+b[i] for i in range(size)]
    t2 = time.time()
    return (t2-t1)

def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a+b
    t2 = time.time()
    return(t2-t1)

t_list = addition_using_list()
t_numpy = addition_using_numpy()
print("List = ", t_list*1000)
print("Numpy = ", t_numpy*1000)


List =  48.2177734375
Numpy =  0.33593177795410156


In [29]:
import numpy as np
a = [1,2,3]
b = np.array(a)
# print(b)
# print(type(b))
b = np.array(a, dtype = str)
# print(b)
# print(type(b))
b = np.ones(3, dtype = int)
# print(b)
b = np.zeros(3, dtype = int)
# print(b)
# 2D array
# 2X3
b = np.ones((2,3), dtype = int)
# print(b)

b = np.full(3,5) # size and fill value required.
# print(b)
b = np.empty([2,3],dtype = int, order = 'C')

a = np.empty(4,dtype=int)
print(a)

[1 1 0 0]


In [48]:
# Arrange and Linespace
b = np.arange(10)
print(b)
b = np.arange(2,10,2, dtype = float)
print(b)

b = np.linspace(2,10,5,dtype=int,endpoint = False) # 50 values with 2 to 10 
print(b)

## Identity and Eye 

b = np.identity(3,dtype = int) # one argument n which nXn
print(b)

b = np.eye(3,4,dtype=int) # 3x4 matrix
print(b)


[0 1 2 3 4 5 6 7 8 9]
[2. 4. 6. 8.]
[2 3 5 6 8]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [56]:
# Random 
b = np.random.rand(2,3)*10 # uniformly distributed b/w 0 to 1 exclusive
b

a = np.array([0,1,2,3])
a.shape

#b = np.random.randint(10,4)
#b
b = np.random.randint(10,size = (4,4))
b

array([[5, 6, 3, 4],
       [2, 6, 7, 4],
       [6, 4, 6, 2],
       [2, 9, 1, 6]])

In [59]:
li = [1,2,3,4,5]
arr = np.array(li)
print(li)
print(arr)
print(li[1:4])
print(arr[1:4])

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[2, 3, 4]
[2 3 4]


In [71]:
li_2D = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr_2D = np.array(li_2D)
print(li_2D)
print(arr_2D)
print(li_2D[2][1])
print(arr_2D[2][1])
print(arr_2D[2,1]) # Accessing 
print(li_2D[1][:3])
print(arr_2D[1][:3])
# Accessing           0         1           2
#print(li_2D[:3][2]) [1,2,3,4],[5,6,7,8],[9,10,11,12]
# Answer is [9,10,11,12]
print(arr_2D[0:2,1:3])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
10
10
10
[5, 6, 7]
[5 6 7]
[[2 3]
 [6 7]]


In [73]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [83]:
a = a+1
c = a + b
c
d = a - b
d
f = a*b
f
h = a / b
h
k = a // b 
k
l = a ** b
l
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin()) # min value index
print(a.max())
print(a.argmax())

[20 17 11 25 27]
100
20.0
11
2
27
4


In [85]:
a > b

array([ True,  True, False,  True,  True])

In [86]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [90]:
print(np.logical_not(a))

[False False False False False]


In [93]:
## Boolean Indexing
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)
print(a)
print(b)
bool_arr = b > 10
new_arr = b[bool_arr]
print(new_arr)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[18 13 19  5  9 14 18 17]
[18 13 19 14 18 17]


In [95]:
new_arr = b[b>10]
print(new_arr)

[18 13 19 14 18 17]


In [98]:
new_arr = b[(b > 10) & (b < 18)]
print(new_arr)

[13 14 17]


In [103]:
a = np.random.randint(1,30,(5,6))
bool_arr = a>20
print(bool_arr)
ans = a[bool_arr]
print(ans)

[[False  True False False False False]
 [False False False False  True False]
 [False False False False False  True]
 [ True False False  True False False]
 [False  True  True False False False]]
[27 27 22 24 27 29 22]


In [106]:
b = a
b[bool_arr] = 100 # bool_array should be in same shape.
print(b)

[[ 11 100   5   6  16  16]
 [ 15   4   8   9 100  19]
 [  5   7  10   9   1 100]
 [100   4  15 100   9  13]
 [  8 100 100  15   3  17]]


In [111]:
print(b)
bool_arr = b[:,1] == 100  # column result in bool_array
print(bool_arr)

b[bool_arr, 1] = 99 # updating the col by mentioning the col index and pass the bool_array
print(b)

[[ 11  99   5   6  16  16]
 [ 15   4   8   9 100  19]
 [  5   7  10   9   1 100]
 [100   4  15 100   9  13]
 [  8  99 100  15   3  17]]
[False False False False False]
[[ 11  99   5   6  16  16]
 [ 15   4   8   9 100  19]
 [  5   7  10   9   1 100]
 [100   4  15 100   9  13]
 [  8  99 100  15   3  17]]
